# Descrição

Este notebook apresenta a primeira versão de um modelo de aprendizado de máquina desenvolvido para prever se um passageiro sobreviveu ao naufrágio do Titanic, utilizando o conjunto de dados clássico [Titanic - Machine Learning from Disaster](https://www.kaggle.com/competitions/titanic/data).

# Módulos

In [1]:
import pandas as pd

# Importação dos dados

In [2]:
# Leitura do arquivo de dados
df = pd.read_csv("dados/train.csv")

In [3]:
# cinco primerias amostras
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Analise Exploratória

In [4]:
# Identificação dos atributos (Colunas)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
# Tipos da dada em cada atributo
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

|Tipo de Dado (dtype)|O que representa|Exemplo|Comportamento com Nulos|
|--------------------|----------------|-------|-----------------------|
|`int64`|Número inteiro|`1`, `500` e `-20`|Não aceita `NaN`, se houver valor ausente será convertido em `float64`|
|`float64`|Número decimal|`3.14`, `10.0` e `-0.5`|Suporte nativo o `NaN` para representa valores ausentes|
|`object`|Texto ou tipos mistos|`"Olá"`, `"A-123"` e `[1,2,3]`|Pode armazenar `None`, `NaN` ou qualquer objeto Python|

In [6]:
# Tamanho da dataframe (Amostra (Número de linhas), Atributos (Número de colunas))
df.shape

(891, 12)

In [7]:
# Resumo descritivo das datafrane
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
# Dados ausentes em cada atributo
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
# Percentual dos dados ausentes em cada atributo
df.isnull().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [10]:
# Dados ausentes em cada amostra
df.isnull().sum(axis=1)

0      1
1      0
2      1
3      0
4      1
      ..
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [11]:
# Percentual de dados ausentes em amostra
df.isnull().mean(axis=1)

0      0.083333
1      0.000000
2      0.083333
3      0.000000
4      0.083333
         ...
886    0.083333
887    0.000000
888    0.166667
889    0.000000
890    0.083333
Length: 891, dtype: float64

# Limpeza dos dados

Descrição da variáveis

|Varíavel|Descrição|Variável|Descrição|
|--------|---------|--------|---------|
|Survived|Sobrevivencia|Pclass|Classe do Bilhete|
|Sex|Sexo|Age|Idade|
|Ticket|Número do Bilhete|Fare|Tarifa de Passageiros|
|Cabin|Número da Cabine|Embarked|Porto de Embarque|
|SibSp|Número de irmãos/cônjugês no navio|Parch|Números de pais/filhos no navio|
|PassengerId|Número de Identificação do passageiro|Name|Nome do passageiro|

1. O Atributo `Survived` indica se o passageiro sobreviveu a tragédia.
> Como o objetivo é prever a sobrevivência, esse atributo já revela antecipadamente a resposta que o modelo deve prever. Esse fenômeno é chamado de ***vazamento de informação***, e por isso o atributo `Survived` precisa ser removido durante a construção do modelo.

2. O Atributo `Name` lista os nomes dos diversos passageiros, o que não se mostra relevante para determinar se ele sobreviveu a tragédia.
3. O atributo `PassengerId` lista o id de identificação de cada passageiro o que se mostrar relevante para criar o modelo de sobrevivência.
4. O atributo `Ticket` é o número de bilhete de cada passageiro não tem relevância em primeiro momento para determina a criação do modelo de sobrevivência

In [12]:
# Criar um dataframe indicando se o passageiro sobreviveu
survived = pd.DataFrame(df['Survived'])

# Mostrar o final do dataframe
survived.tail()

     Survived
886         0
887         1
888         0
889         1
890         0

In [13]:
# Excluir os Atributos 'PassengerId', 'Survived', 'Name' e 'Ticket' do dataframe original
df.drop(columns=['PassengerId','Survived', 'Name', 'Ticket'], inplace=True)

# Mostrar o final do dataframe atual
df.tail()

     Pclass     Sex   Age  SibSp  Parch   Fare Cabin Embarked
886       2    male  27.0      0      0  13.00   NaN        S
887       1  female  19.0      0      0  30.00   B42        S
888       3  female   NaN      1      2  23.45   NaN        S
889       1    male  26.0      0      0  30.00  C148        C
890       3    male  32.0      0      0   7.75   NaN        Q

## Variável Dummy

Uma variável dummy é utilizada para representar variáveis categóricas por meio de valores binários (0 e 1). Nesse caso, empregaremos esse tipo de variável para codificar as indicações de sexo da seguinte maneira:
|Sexo|Valor|
|----|-----|
|female|0|
|male|1|

In [14]:
# Trocar de valores para variável categórica 'Sex'
for i in range(len(df)):
    if df.loc[i,'Sex'] == 'female':
        df.loc[i,'Sex'] = 0
    else:
        df.loc[i,'Sex'] = 1

# Mostra o dataframe
df.head()

   Pclass Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       3   1  22.0      1      0   7.2500   NaN        S
1       1   0  38.0      1      0  71.2833   C85        C
2       3   0  26.0      0      0   7.9250   NaN        S
3       1   0  35.0      1      0  53.1000  C123        S
4       3   1  35.0      0      0   8.0500   NaN        S

Para `Embarked` transformaremos em uma variável dummy, como `Embarked` apresenta três categorias devemos criar duas variáveis dummys:
1. `Cherbourg` com valores 0 ou 1, sendo 1 quando `Embarked` tivesse sindo classificado como `C` e 0 quando não recebeu esse valor.
2. `Queenstown` com valor 0 ou 1, sendo 1 quando `Embarked` tivesse sindo classificado como `Q`e 0 quando não recebeu esse valor.
3. Quando `Cherbourg` e `Queenstown` receberem valor 0, saberemos que `Embarked` foi classificado como `S`.

Quando temos $k$ categorias, são necessários $k-1$ categorias variáveis dummy. Isso é necessários para evitamos ***Multicolinearidade*** que é quando duas ou mais variáveis independentes apresentam uma alta correlação.

****Tabela de Representação****
|Categorias|Cherbourg|Queenstown|
|:--------:|:-------:|:--------:|
|`C`|1|0|
|`Q`|0|1|
|`S`|0|0|

In [15]:
# Lista de lista para transformar 'Embarked' em um variável Dummy
embarked = []

# Determinar o valor de cada variável Dummy
for index in range(len(df)):
    if df.loc[index,'Embarked'] == 'C':
        embarked.append([1,0])
    elif df.loc[index,'Embarked'] == 'Q':
        embarked.append([0,1])
    else:
        embarked.append([0,0])

# Dataframe como o atributo 'Embarked' transformando em um variável dummy de acordo com suas categórias
embarked = pd.DataFrame(embarked, columns=['Cherbourg','Queenstown'])

# Mostra o final dataframe
embarked.tail()

     Cherbourg  Queenstown
886          0           0
887          0           0
888          0           0
889          1           0
890          0           1

In [16]:
# Concatenando os dois dataframe embarked e df
df = pd.concat([df,embarked], axis=1)

# Mostrar o Dataframe
df

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cherbourg,Queenstown
0,3,1,22.0,1,0,7.2500,NaN,S,0,0
1,1,0,38.0,1,0,71.2833,C85,C,1,0
2,3,0,26.0,0,0,7.9250,NaN,S,0,0
3,1,0,35.0,1,0,53.1000,C123,S,0,0
4,3,1,35.0,0,0,8.0500,NaN,S,0,0
...,...,...,...,...,...,...,...,...,...,...
886,2,1,27.0,0,0,13.0000,NaN,S,0,0
887,1,0,19.0,0,0,30.0000,B42,S,0,0
888,3,0,NaN,1,2,23.4500,NaN,S,0,0
889,1,1,26.0,0,0,30.0000,C148,C,1,0
890,3,1,32.0,0,0,7.7500,NaN,Q,0,1

In [17]:
# Excluir o Atributo 'Embarked' que não é mais necessário foi trocado pelos atributos 'Cherbourg', 'Queenstown' e 'Southampton'
df.drop(columns=['Embarked'], inplace=True)

# Mostra o dataframe
df

     Pclass Sex   Age  SibSp  Parch     Fare Cabin  Cherbourg  Queenstown
0         3   1  22.0      1      0   7.2500   NaN          0           0
1         1   0  38.0      1      0  71.2833   C85          1           0
2         3   0  26.0      0      0   7.9250   NaN          0           0
3         1   0  35.0      1      0  53.1000  C123          0           0
4         3   1  35.0      0      0   8.0500   NaN          0           0
..      ...  ..   ...    ...    ...      ...   ...        ...         ...
886       2   1  27.0      0      0  13.0000   NaN          0           0
887       1   0  19.0      0      0  30.0000   B42          0           0
888       3   0   NaN      1      2  23.4500   NaN          0           0
889       1   1  26.0      0      0  30.0000  C148          1           0
890       3   1  32.0      0      0   7.7500   NaN          0           1

[891 rows x 9 columns]

## Dados ausentes

In [18]:
# Excluir os dados do Atributo 'Cabin' por cerca de 77% desses dados serem NaN
df.drop(columns=['Cabin'], inplace=True)

# Mostra o DataFrame Atualizado
df.head()

   Pclass Sex   Age  SibSp  Parch     Fare  Cherbourg  Queenstown
0       3   1  22.0      1      0   7.2500          0           0
1       1   0  38.0      1      0  71.2833          1           0
2       3   0  26.0      0      0   7.9250          0           0
3       1   0  35.0      1      0  53.1000          0           0
4       3   1  35.0      0      0   8.0500          0           0

In [19]:
def ausentes(DataFrame, quantidade=False):
    # Identificação da posição dos valores ausentes
    '''
    Paramêtros:
        DataFrame: DataFrame do Pandas
        quantidade (bool): True mostra indica a quantidade de dados ausentes

    Return:
        list: Uma lista de tuplas onde temos (linha,coluna) de cada valor ausente
        int: Quantidade de dados ausentes
    '''
    ausentes = [] # Armazenar a posição da cada valor ausente
    for index in range(len(df.index)):
        for columns in range(len(df.columns)):
            if pd.isna(df.iloc[index,columns]):
                ausentes.append((index,columns))

    return len(ausentes) if quantidade else ausentes

In [20]:
# Lista de valores ausentes
valores_ausentes = ausentes(df)

# Indica a quantidade de valores ausentes
print(f'Quantidade de valores ausentes: {len(valores_ausentes)}')

# Exclusão de toda as amostras com valores ausentes restantes
for posicao in valores_ausentes:
    try:  # Bloco try-except é para evitar quebrar de código já que tera index repetidos
        df.drop(posicao[0], inplace=True)
    except:
        continue

# Atualização dos index
df.index = df.index

# Mostrar o dataframe
df.head()

Quantidade de valores ausentes: 177

   Pclass Sex   Age  SibSp  Parch     Fare  Cherbourg  Queenstown
0       3   1  22.0      1      0   7.2500          0           0
1       1   0  38.0      1      0  71.2833          1           0
2       3   0  26.0      0      0   7.9250          0           0
3       1   0  35.0      1      0  53.1000          0           0
4       3   1  35.0      0      0   8.0500          0           0

Assim como excluímos as amostras que possuem valores ausentes, devemos aplicar o mesmo procedimento aos dados referentes à indicação dos passageiros sobreviventes, para manter a compatibilidade entre os dataframes

In [21]:
# Exclusão de toda as amostras com valores ausentes
for posicao in valores_ausentes:
    try:  # Bloco try-except é para evitar quebrar de código já que tera index repetidos
        survived.drop(posicao[0], inplace=True)
    except:
        continue

# Atualização dos index
survived.index = survived.index

# Mostrar o dataframe
survived.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [22]:
# Quantidade de valores ausente no dataframe atual
print(f'Quantidade de valores ausentes: {ausentes(df, quantidade=True)}')

# Tamanho atual do DataFrame (Amostra, Atributos)
df.shape

Quantidade de valores ausentes: 0

(714, 8)

# Transformação dos dados

A transformação dos dados é essencial para garanti a criação de modelos de predição coerentes já que determinados tipos de modelos aceitam somente determinando padrão estatístico de dados inseridos.

A transformação é importante por:
> **Preparar os dados para análise**\
> **Validação de pressupostos estatísticos**\
> **Redução de vieses e ruídos**\
> **Melhoria da interpretação**

Pontos de atenção:
> **Nem toda transformação é necessária**\
> **Intepretação dos resultados**\
> **Transparência**

## Normalização

Sendo $X$ o valor que será transformado, $X_{Min}$ o menor valor da série dos dados e $X_{Max}$ o maior valor da série de dados, a normalização do valor $X$ será dado por:
    
<center> $X^{'}=\displaystyle\frac{X-X_{Min}}{X_{Max}-X_{Min}}$ <center>

In [23]:
# Dataframe com valores normalizados
normalizados = pd.DataFrame()

In [24]:
# Inserir valores normalizados
for i in df.columns:
    i_max = df[i].max() # Maior valor da i-coluna
    i_min = df[i].min() # Menor valor da i-coluna
    normalizados[i] = [(valor - i_min)/(i_max - i_min) for valor in df[i]] # Arry com dados da i-coluna

In [25]:
# Salvado os dados normalizados e padronizados
normalizados.to_csv("Dados\\normalizados.csv", index = False)

## Padronização

Sendo $X$ o valor que será transfornado, $\mu$ a média e $\sigma$ o desvio padrão dos dados, a padronização do valor $X$ será dados por:

<center>$z = \displaystyle\frac{X - \mu}{\sigma}$<center>

Onde o valor $z$ é chamado de z-score.

In [26]:
# Dataframe com valores padronizados
padronizados = pd.DataFrame()

In [27]:
# Inserir valores padronizados
for i in df.columns:
    media = df[i].mean() # Média dos valores na i-coluna
    desvio_padrao = df[i].std() # Desvio padrão dos valores na i-coluna
    padronizados[i] = [(valor - media)/desvio_padrao for valor in df[i]] # Arry com dados da i-coluna

In [28]:
# Salvado os dados padronizados
padronizados.to_csv("Dados\\padronizados.csv", index = False)

## Função de Transformação

Como dispomos de duas bases de dados:

> 1. Uma destinada à criação do modelo
> 2. Outra destinada à avaliação do modelo

A base de dados utilizada para avaliação apresenta exatamente a mesma estrutura e organização da base usada na criação do modelo. Por consequência, antes de avaliarmos o modelo diretamente pelo sklearn, devemos aplicar o mesmo tratamento de limpeza e organização dos dados. Para isso, criaremos uma função em Python que receba a base de dados bruta, execute toda a limpeza necessária e retorne um DataFrame pronto para ser utilizado tanto no treinamento quanto na avaliação do modelo.

In [29]:
def limpeza(dados, padronizados=False, normalizados=False):
    '''
    Paramêtros:
        Dados: DataFrame pandas de dados brutos
        padronizados: Se True retorn o dataframe com dados padronizados
        normalizados: Se True retorn o dataframe com dados normalizados

    Return:
        Dataframe do pandas
    '''
   
    # Excluir os Atributos 'PassengerId', 'Survived', 'Name' e 'Ticket' do dataframe original
    dados = dados.drop(columns=['PassengerId', 'Name', 'Ticket'])

    # Excluir os dados do Atributo 'Cabin' por cerca de 77% dos dados na treinamento do modelo serem NaN
    dados = dados.drop(columns=['Cabin'])

    # Remove linhas que tenham pelo menos um NaN
    dados = dados.dropna()

    # Organizado os index
    dados.index = range(len(dados))

    # Transformação da variável sexo
    for index in range(len(dados)):
        if dados.loc[index, "Sex"] == "male":
            dados.loc[index, "Sex"] = 1
        else:
            dados.loc[index, "Sex"] = 0
  
    # Lista para variáveis dummy 'Cherbourg' e 'Queenstown'
    cherbourg, queenstown = [], []
    
    # Determinar o valor de cada variável Dummy
    for index in range(len(dados)):
        if dados.loc[index,'Embarked'] == 'C':
            cherbourg.append(1)
            queenstown.append(0)
        elif dados.loc[index,'Embarked'] == 'Q':
            cherbourg.append(0)
            queenstown.append(1)
        else: # Quanto aparece o valor `S`
            cherbourg.append(0)
            queenstown.append(0)

    # Adiciona os atributos 'Cherbourg' e 'Queenstown' 
    dados['cherbourg'] = cherbourg
    dados['queenstown'] = queenstown
    
    # Excluir o Atributo 'Embarked' que não é mais necessário
    dados = dados.drop(columns=['Embarked'])

    # Determinar o "Tipo de dataframe"
    if padronizados:
        dados = (dados - dados.mean())/dados.std() # padronizado
        return dados
    elif normalizados:
        dados = (dados - dados.min())/(dados.max() - dados.min()) # Normalizado
        return dados
    else: # Retorna os dados já limpos
        return dados

# Treinamento

Teorema **No free Lunch** afirma que para todos os problemas possíveis algoritmos de aprendizagem apresentam básicamente o mesmo desempenho. De outra forma, qualquer algoritmo de aprendizagem se mostrar será excelente/excepicional em determinado problema, porém mediocre em outro, de forma que na média todos os algoritmos teram o mesmo desempenhom quando consideramos todos os problemas possíveis que algoritmos podem se aplicados.

In [30]:
# Importação dos modelos para treino
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [31]:
# Salvar os dados dos modelos treinados
from joblib import dump

# Tratamenoto de datas
import datetime

In [32]:
# Criar instâncias dos modelos
logistic_regression = LogisticRegression()
decision_tree = DecisionTreeClassifier(random_state=31)
random_forest = RandomForestClassifier(random_state=31)
knn = KNeighborsClassifier()
svm = SVC()

# Lista de modelos
modelos = [logistic_regression, decision_tree, random_forest, knn, svm]

In [33]:
# Dados para treino
x_treino = padronizados[padronizados.columns]
y_treino = survived["Survived"]

In [34]:
# Diciónario vázio para adicioanar as informações da cada modelo
modelos_infor = {}

# Inserir as informações
for modelo in modelos:
    instancia = modelo.fit(x_treino, y_treino)  # Treinamedo do modelo
    modelos_infor[str(modelo)] = { 'Instancia_do_Modelo': instancia.fit(x_treino, y_treino),
                                   'Data_de_Treinamento': datetime.date.today().isoformat(),
                                   'Parametros_do_Modelo': instancia.get_params()
                                 }

In [35]:
# Salvando todos os modelos e metadados em um único arquivo
dump(modelos_infor, "modelos_treinados.joblib")

['modelos_treinados.joblib']

# Avaliação

In [36]:
# Métricas de avaliação
from sklearn.metrics import precision_score # Valor Preditivo Positivo
from sklearn.metrics import recall_score # Sensibilidade
from sklearn.metrics import f1_score # F1-Score

In [37]:
# Carregar os dados dos modelos salvos
from joblib import load

In [38]:
# Leitura do arquivo de teste
teste = pd.read_csv("dados/test.csv")
survived = pd.read_csv("dados/gender_submission.csv")

In [39]:
# Carregando depois
modelos_carregados = load("modelos_treinados.joblib")

In [40]:
for chave in modelos_carregados:
    modelos_carregados[chave]['Metricas'] = {'precision_score': precision_score(y_true, y_pred),
                                             'recall_score': recall_score(y_true, y_pred),
                                             'f1_score': f1_score(y_true, y_pred)
}

NameError: name 'y_true' is not defined

# Anexos

## Anexo A - Documentação das funções

| Função | Descrição | Função | Descrição | Função | Descrição |
|--------|-----------|--------|-----------|--------|-----------|
|[lista.append](https://docs.python.org/pt-br/3/library/stdtypes.html#list.append)|Adiciona valores a uma lista|[pd.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)|Leitura de arquivos .csv| [pd.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) | Transformar estruturas em dataframe |
| [df.shape](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html#pandas.DataFrame.shape) | Tamanho do DataFrame | [df.describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe) | Descrição estatística básica do DataFrame | [pd.concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat) | Unir dois DataFrames |
| [df.sum](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas.DataFrame.sum) | Soma dos valores | [df.mean](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html#pandas.DataFrame.mean) | Média dos valores | [df.columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html#pandas.DataFrame.columns)|Identificação dos atributos (Nome das colunas)|
| [df.dtypes](https://pandas.pydata.org/pandas-docs/version/2.2/reference/api/pandas.DataFrame.dtypes.html#pandas.DataFrame.dtypes) | Tipo de dado | [df.isnull](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html#pandas.DataFrame.isnull) | Determina se a célula tem algum valor | [df.tail](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail) | Retorna as últimas amostras |
| [df.head](https://pandas.pydata.org/pandas-docs/version/2.2/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head) | Retorna as primeiras amostras | [df.drop](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html#pandas.DataFrame.drop) | Elimina amostra/Atributos | [df.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html#pandas.DataFrame.isna) | Detectar valores faltantes |
| [df.index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html#pandas.DataFrame.index) | Índice do DataFrame | [df.loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) | Acesso por Rótulos (Nome da linha, nome da coluna) | [df.iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc) | Acesso por índices (linha, coluna) |

## Anexo B - Diferença entre `==` e `is` e `None` e `NaN`

1. `None`: É um objeto nativo do Python (tipo NoneType) que representa o valor "nulo" ou a ausência total de um valor. É o padrão do Python para indicar que algo não existe.
2. `NaN` (Not a Number): É um valor de ponto flutuante (tipo float) implementado pelo NumPy. Ele é usado especificamente para representar dados numéricos ausentes ou resultados de operações matemáticas indefinidas (como 0/0). 

||Origem|Uso Principal|Performace|Comparação|
|:----:|----------------------------|------------------|------|--|
|`None`|Nativo do python (`NoneType`)|Estrutura de dados|Lento |`None == None` é `true`|
|`NaN` |Biblioteca Numpy (`float`)  |Cálculo científico|Rápido|`NaN == NaN` é `False`|

3. `==` (Igualdade): Compara se o conteúdo ou os valores de dois objetos são iguais.
4. `is` (Identidade): Verifica se duas variáveis apontam para o exato mesmo objeto no mesmo endereço de memória. 

||Compara|Característica|Exemplo|
|---|---|---|---|
|`==`|O valor dos objetos|Operado de igualdade|`[1, 2] == [1, 2]` retorna `True`|
|`is`|O endereço de memória|Operador de identidade|`[1, 2] is [1, 2]` retorna `False`|